### ISSUE TITLE
博客中的图片失效了

### ISSUE THREAD

**Issue by Caffe-del** [DaisukeZJY/CopyTest#1]
博客中的图片失效了

**Comment by feng-tianyou** [comment]
可以看这个[掘金](https://juejin.im/post/6844903629338460167)

**Comment by Caffe-del** [comment]
> 可以看这个[掘金](https://juejin.im/post/6844903629338460167)

404 啦，删除了吧？

**Comment by feng-tianyou** [comment]
不知道什么原因，我重新发布，审核过了再发给你吧，哈哈哈哈哈

**Comment by feng-tianyou** [comment]
可以看了
